# disease name
TUBERCULOSIS_AND_HIV = 'tuberculosis_and_hiv'

# risk names
HOUSEHOLD_TUBERCULOSIS = 'household_tuberculosis'
RISK_DISTRIBUTION_TYPE = 'dichotomous'


#  state names
ACTIVETB_POSITIVE_HIV = 'activetb_positive_hiv'
ACTIVETB_SUSCEPTIBLE_HIV = 'activetb_susceptible_hiv'
LTBI_SUSCEPTIBLE_HIV = 'ltbi_susceptible_hiv'
LTBI_POSITIVE_HIV = 'ltbi_positive_hiv'
SUSCEPTIBLE_TB_POSITIVE_HIV = 'susceptible_tb_positive_hiv'
SUSCEPTIBLE_TB_SUSCEPTIBLE_HIV = 'susceptible_tb_susceptible_hiv'


# transition names (from, to)
ACTIVETB_SUSCEPTIBLE_HIV_TO_ACTIVETB_POSITIVE_HIV = 'activetb_susceptible_hiv_to_activetb_positive_hiv'
ACTIVETB_SUSCEPTIBLE_HIV_TO_SUSCEPTIBLE_TB_SUSCEPTIBLE_HIV = \
    'activetb_susceptible_hiv_to_susceptible_tb_susceptible_hiv'
ACTIVETB_POSITIVE_HIV_TO_SUSCEPTIBLE_TB_POSITIVE_HIV = 'activetb_positive_hiv_to_susceptible_tb_positive_hiv'
LTBI_SUSCEPTIBLE_HIV_TO_ACTIVETB_SUSCEPTIBLE_HIV = 'ltbi_susceptible_hiv_to_activetb_susceptible_hiv'
LTBI_SUSCEPTIBLE_HIV_TO_LTBI_POSITIVE_HIV = 'ltbi_susceptible_hiv_to_ltbi_positive_hiv'
LTBI_POSITIVE_HIV_TO_ACTIVETB_POSITIVE_HIV = 'ltbi_positive_hiv_to_activetb_positive_hiv'
SUSCEPTIBLE_TB_POSITIVE_HIV_TO_LTBI_POSITIVE_HIV = 'susceptible_tb_positive_hiv_to_ltbi_positive_hiv'
SUSCEPTIBLE_TB_SUSCEPTIBLE_HIV_TO_LTBI_SUSCEPTIBLE_HIV = 'susceptible_tb_susceptible_hiv_to_ltbi_susceptible_hiv'
SUSCEPTIBLE_TB_SUSCEPTIBLE_HIV_TO_SUSCEPTIBLE_TB_POSITIVE_HIV = 'susceptible_tb_susceptible_hiv_to_susceptible_tb_positive_hiv'
